### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by DoctorArchives** [GitPois1x/DragonLoot#1]
Mixin apply failed dragonloot.mixins.json:AnvilScreenHandlerMixin -> net.minecraft.class_1706: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1706::updateResultMixin with priority 1000 cannot inject into net/minecraft/class_1706::method_24928()V merged by cn.enaium.noexpensive.mixin.AnvilScreenHandlerMixin with priority 1000 [PREINJECT Applicator Phase -> dragonloot.mixins.json:AnvilScreenHandlerMixin -> Prepare Injections ->  -> handler$znj000$updateResultMixin(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1706::updateResultMixin with priority 1000 cannot inject into net/minecraft/class_1706::method_24928()V merged by cn.enaium.noexpensive.mixin.AnvilScreenHandlerMixin with priority 1000 [PREINJECT Applicator Phase -> dragonloot.mixins.json:AnvilScreenHandlerMixin -> Prepare Injections ->  -> handler$znj000$updateResultMixin(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2246.<clinit>(class_2246.java:426)
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458$$Lambda$232/844133497.get(Unknown Source)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at net.minecraft.class_5458$$Lambda$240/16957838.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:237)
	at io.github.cottonmc.jankson.JanksonFactory.builder(JanksonFactory.java:85)
	at io.github.cottonmc.jankson.JanksonFactory.createJankson(JanksonFactory.java:159)
	at io.github.redstoneparadox.paradoxconfig.serialization.jankson.JanksonConfigSerializer.<init>(JanksonConfigSerializer.java:16)
	at io.github.redstoneparadox.nicetohave.config.Config.<clinit>(Config.java:13)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.github.redstoneparadox.paradoxconfig.util.ReflectionUtil.getClassForName(ReflectionUtil.java:13)
	at io.github.redstoneparadox.paradoxconfig.ParadoxConfig.initConfigs$paradox_config(ParadoxConfig.java:66)
	at io.github.redstoneparadox.paradoxconfig.ParadoxConfig.onPreLaunch(ParadoxConfig.java:21)
	at net.fabricmc.loader.launch.knot.Knot$$Lambda$88/1961595039.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

**Comment by Globox1997** [comment]
When did this happen?

**Comment by Globox1997** [comment]
NoExpensive mod by enaium is the issue - the mod has no hub link so I guess it's closed source (ARR too) but the issue has to be on enaiums side cause I'm using regular injections, enaium probably redirect or overwrite which makes it incompatible with all other mods which try to use the breaking method.

**Comment by DoctorArchives** [comment]
> When did this happen?

Pretty sure when this mod was released, I tried it but it had this error, now it seems to be working fine, unfortunately, I guess I can't use the no expensive mod, the only reason why that's useful is that I also use EnchantsPlus by mrgoose374, and I'm pretty sure I'd have issues with applying enchants by that I mean putting multiple high level enchants but I'll see what I can do, not sure if this is true [edit: I tested this and seems to be working okay without the no experience mod] but anyways, thanks for narrowing it down for me on what the problem was.

**Comment by DoctorArchives** [comment]
Also, one thing I wanted to mention is that I noticed that the textures kind of mess up with capes, in my case an optifine cape ruins the wing textures but if I take off the cape the textures seem to work fine, just wanted to point that out for you, not sure if it's possible to fix or not.

**Comment by Globox1997** [comment]
Thanks for informing us about the cape bug :)
The dragon anvil is more than just an anvil which never breaks so just try it out :D
