### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by InsaanNotFound** [GitPois1x/DragonLoot#6]
```
[23:34:24] [main/FATAL]: Unreported exception thrown!
org.spongepowered.asm.mixin.injection.callback.CancellationException: The call method_17369 is not cancellable.
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.setReturnValue(CallbackInfoReturnable.java:106) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.minecraft.screen.AnvilScreenHandler.handler$bem000$getLevelCostMixin(AnvilScreenHandler:1075) ~[?:?]
	at net.minecraft.screen.AnvilScreenHandler.getLevelCost(AnvilScreenHandler) ~[?:?]
	at net.minecraft.client.gui.screen.ingame.AnvilScreen.handler$fag001$drawForeground(AnvilScreen:2531) ~[?:?]
	at net.minecraft.client.gui.screen.ingame.AnvilScreen.drawForeground(AnvilScreen) ~[?:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:142) ~[?:?]
	at net.minecraft.client.gui.screen.ingame.ForgingScreen.render(ForgingScreen:42) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:616) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.MinecraftClient.handler$bjd000$afterCrashHandled(MinecraftClient:12404) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:699) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[23:34:24] [main/FATAL]: Minecraft ran into a problem! Report saved to: C:\Users\Seba\Desktop\Gry\MultiMC\instances\Fabulously-Optimized-1.4.2\minecraft\crash-reports\crash-2021-01-20_23.34.24-client.txt
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2021-01-20 23:34:24 CET
Description: Rendering screen

org.spongepowered.asm.mixin.injection.callback.CancellationException: The call method_17369 is not cancellable.
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101)
    at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.setReturnValue(CallbackInfoReturnable.java:106)
    at net.minecraft.screen.AnvilScreenHandler.handler$bem000$getLevelCostMixin(AnvilScreenHandler:1075)
    at net.minecraft.screen.AnvilScreenHandler.getLevelCost(AnvilScreenHandler)
    at net.minecraft.client.gui.screen.ingame.AnvilScreen.handler$fag001$drawForeground(AnvilScreen:2531)
    at net.minecraft.client.gui.screen.ingame.AnvilScreen.drawForeground(AnvilScreen)
    at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:142)
    at net.minecraft.client.gui.screen.ingame.ForgingScreen.render(ForgingScreen:42)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:616)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.MinecraftClient.handler$bjd000$afterCrashHandled(MinecraftClient:12404)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:699)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

To reproduce, try to enchant something needing more than 30 levels in Dragon Anvil.
Using Fair Enchanting mod, idk if it could be conflicting

**Comment by InsaanNotFound** [comment]
Also will post this
Used MixinTrace
```
Mixins in Stacktrace: net.minecraft.class_1706:
                        de.siphalor.nbtcrafting.mixin.anvil.MixinAnvilContainer (nbtcrafting.mixins.json)
                        top.theillusivec4.colytra.loader.mixin.AnvilScreenHandlerMixin (colytra.mixins.json)
                        net.nile.enchant.fix.mixin.AnvilAccessor (nenchantfix.mixins.json)
                        svenhjol.charm.mixin.accessor.AnvilScreenHandlerAccessor (charm.mixins.json)
                        svenhjol.charm.mixin.AnvilScreenHandlerMixin (charm.mixins.json)
                        io.github.apace100.originsclasses.mixin.AnvilScreenHandlerMixin (origins-classes.mixins.json)
                        net.dragonloot.mixin.AnvilScreenHandlerMixin (dragonloot.mixins.json)
                        ru.betterend.mixin.common.AnvilScreenHandlerMixin (betterend.mixins.common.json)
                        top.theillusivec4.colytra.loader.mixin.AnvilScreenHandlerAccessor (colytra.mixins.json)
                        net.nile.enchant.fix.mixin.AnvilFix (nenchantfix.mixins.json)
                        net.cerulan.fairenchanting.mixin.MixinAnvilScreenHandler (fairenchanting.mixins.json)
                        draylar.intotheomega.mixin.AnvilScreenHandlerMixin (intotheomega.mixins.json)
                        net.minecraft.class_471:
                        draylar.cu.mixin.AnvilScreenMixin (colorunchained.mixins.json)
                        net.nile.enchant.fix.mixin.AnvilScreenFix (nenchantfix.mixins.json)
                        de.siphalor.nbtcrafting.mixin.client.AnvilScreenAccessor (nbtcrafting.mixins.json)
                        ru.betterend.mixin.client.AnvilScreenMixin (betterend.mixins.client.json)
                        svenhjol.charm.mixin.AnvilScreenMixin (charm.mixins.json)
                        net.nile.enchant.fix.mixin.AnvilScreenAccessor (nenchantfix.mixins.json)
                        net.minecraft.class_465:
                        tfar.dankstorage.mixin.AbstractContainerScreenMixin (dankstorage.mixins.json)
```

**Comment by InsaanNotFound** [comment]
I tested everything out today, mod works fine on its own, but crashes with any other mod modifying and/or adding enchantments (NileEnchantmentFix, Minecraft Dungeons Weapons, Enchanting Plus, etc.) when xp cost is more than 30 levels while using Dragon Anvil. 
Crash log is always the same. We need a fix.

**Comment by Globox1997** [comment]
[dragonloot-1.0.5.zip](https://github.com/GitPois1x/DragonLoot/files/5848577/dragonloot-1.0.5.zip)
please test this version :) (you need to extract the jar file)

**Comment by InsaanNotFound** [comment]
Tested with NileEnchantmentFix and few other mods, everything works fine now :)
