### ISSUE TITLE
Game crashes when we throw a dragon trident

### ISSUE THREAD

**Issue by TaianRmos** [GitPois1x/DragonLoot#81]
Hi, 
I was playing with tridents and found out that the game immediately crashes when you try to throw a trident that was upgraded with a dragon scale. If the trident has Riptide at any level it works fine, but if you have to throw the trident the game crashes with the following error:

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_1665.<init>(net.minecraft.class_1299, net.minecraft.class_1309, net.minecraft.class_1937)'

Exit code: -805306369

I tried to put loyalty on the trident but the result was the same.
The test was made on minecraft fabric 1.20.4 with fabric loader 0.15.7. I also have other mods installed if that can help, here's a list of the mods I have:
![image](https://github.com/GitPois1x/DragonLoot/assets/87705384/28618645-e245-4842-b52d-b3757916106f)

Also, this is the full error file generated:

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-02-29 22:37:43
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_1665.<init>(net.minecraft.class_1299, net.minecraft.class_1309, net.minecraft.class_1937)'
	at net.dragonloot.entity.DragonTridentEntity.<init>(DragonTridentEntity.java:44)
	at net.dragonloot.item.DragonTridentItem.method_7840(DragonTridentItem.java:45)
	at net.minecraft.class_1799.method_7930(class_1799.java:540)
	at net.minecraft.class_1309.method_6075(class_1309.java:3217)
	at net.minecraft.class_3244.redirect$zge000$carpet$onStopUsing(class_3244.java:4032)
	at net.minecraft.class_3244.method_12066(class_3244.java:1072)
	at net.minecraft.class_2846.method_12361(class_2846.java:42)
	at net.minecraft.class_2846.method_11054(class_2846.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 651349112 bytes (621 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072.00
	Graphics card #0 deviceId: 0x1c02
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4612
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37568.63
	Virtual memory used (MB): 14133.43
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 7.12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		armorposer: Armor Poser 4.1.1
		camerautils: Camera Utils 1.20.4-1.0.8
		cardinal-components: Cardinal Components API 5.4.0
			cardinal-components-base: Cardinal Components API (base) 5.4.0
			cardinal-components-block: Cardinal Components API (blocks) 5.4.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.4.0
			cardinal-components-entity: Cardinal Components API (entities) 5.4.0
			cardinal-components-item: Cardinal Components API (items) 5.4.0
			cardinal-components-level: Cardinal Components API (world saves) 5.4.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.4.0
			cardinal-components-world: Cardinal Components API (worlds) 5.4.0
		carpet: Carpet Mod 1.4.128+v231205
		carpet-fixes: Carpet Fixes 1.20-1.17.0
			conditional-mixin: conditional mixin 0.3.1
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		connectedglass: Connected Glass 1.1.11
		dragonloot: DragonLoot 1.1.4
		fabric-api: Fabric API 0.96.3+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.13+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.2+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.2+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.24+f9b333cc4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.63+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.12+080016e44f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.1+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.11+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		freecam: Freecam (Modrinth Edition) 1.2.3
		fusion: Fusion 1.1.0+d
		indium: Indium 1.0.30+mc1.20.4
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.4+1.20.4
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.3+1.20.2
		lithium: Lithium 0.12.1
		malilib: MaLiLib 0.18.1
		minecraft: Minecraft 1.20.4
		minihud: MiniHUD 0.30.2
		modmenu: Mod Menu 9.0.0
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.4-build.102
		shulkerboxtooltip: Shulker Box Tooltip 4.0.8+1.20.4
		shulkerplus: ShulkerPlus 1.0.7
		sodium: Sodium 0.5.8+mc1.20.4
		sodium-extra: Sodium Extra 0.5.4+mc1.20.4-build.116
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		travelersbackpack: Traveler's Backpack 1.20.4-9.4.0
		voicechat: Simple Voice Chat 1.20.4-2.5.4
		xaerominimap: Xaero's Minimap 23.9.7
		xaeroworldmap: Xaero's World Map 1.37.8
	Loaded Shaderpack: ComplementaryReimagined_r5.1.1.zip
		Profile: MEDIUM (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['TaianRmos'/25, l='ServerLevel[Redstone]', x=-32.66, y=40.00, z=401.58]]
	Data Packs: vanilla, fabric, connectedglass (incompatible), dragonloot, fabric-convention-tags-v1, supermartijn642corelib (incompatible), travelersbackpack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.7-1.20.4
```

Hope you can fix it ! Thank you !

**Comment by Globox1997** [comment]
This mod is not made for the version 1.20.4. Use this mod for either 1.20.1 or 1.21.1
