### ISSUE TITLE
Dragon Trident crashing on impact with any mob

### ISSUE THREAD

**Issue by RaphaelPierog** [GitPois1x/DragonLoot#95]
I made a modpack for my minecraft server and there is a problem that my friends now need to avoid Dragon Trident. I deleted BetterTridents mod but it didn't help because everytime someone throws Dragon Trident at any mob, server freezes/crashes and even if you do it in singleplayer it crashes the whole world and you lose the save
here's the crash log when I threw the trident at random entity.
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-12-13 08:50:23
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_57825(net.minecraft.class_9331, Object)" because "$$0" is null
  at knot//net.minecraft.class_1890.method_8220(class_1890.java:122)
  at knot//net.minecraft.class_1890.method_60120(class_1890.java:171)
  at knot//net.dragonloot.entity.DragonTridentEntity.method_7454(DragonTridentEntity.java:135)
  at knot//net.minecraft.class_1676.method_7488(class_1676.java:208)
  at knot//net.minecraft.class_1676.method_59860(class_1676.java:182)
  at knot//net.minecraft.class_1665.method_5773(class_1665.java:248)
  at knot//net.dragonloot.entity.DragonTridentEntity.method_5773(DragonTridentEntity.java:95)
  at knot//net.minecraft.class_3218.mixinextras$bridge$method_5773$234(class_3218.java)
  at knot//net.minecraft.class_3218.wrapOperation$ffg000$puzzleslib$tickNonPassenger(class_3218.java:13797)
  at knot//net.minecraft.class_3218.method_18762(class_3218.java:770)
  at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
  at knot//net.minecraft.class_3218.method_31420(class_3218.java:408)
  at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
  at knot//net.minecraft.class_3218.method_18765(class_3218.java:372)
  at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
  at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
  at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
  at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
  at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
  at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
  at knot//net.minecraft.class_1890.method_8220(class_1890.java:122)
  at knot//net.minecraft.class_1890.method_60120(class_1890.java:171)
  at knot//net.dragonloot.entity.DragonTridentEntity.method_7454(DragonTridentEntity.java:135)
  at knot//net.minecraft.class_1676.method_7488(class_1676.java:208)
  at knot//net.minecraft.class_1676.method_59860(class_1676.java:182)
  at knot//net.minecraft.class_1665.method_5773(class_1665.java:248)
  at knot//net.dragonloot.entity.DragonTridentEntity.method_5773(DragonTridentEntity.java:95)
  at knot//net.minecraft.class_3218.mixinextras$bridge$method_5773$234(class_3218.java)
  at knot//net.minecraft.class_3218.wrapOperation$ffg000$puzzleslib$tickNonPassenger(class_3218.java:13797)
  at knot//net.minecraft.class_3218.method_18762(class_3218.java:770)
  at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
  at knot//net.minecraft.class_3218.method_31420(class_3218.java:408)
  at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
  Entity Type: dragonloot:dragon_trident (net.dragonloot.entity.DragonTridentEntity)
  Entity ID: 4628
  Entity Name: Dragon Trident
  Entity's Exact location: -137.11, 73.34, -63.53
  Entity's Block location: World: (-138,73,-64), Section: (at 6,9,0 in -9,4,-4; chunk contains blocks -144,-64,-64 to -129,319,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
  Entity's Momentum: 2.29, -0.16, -0.82
  Entity's Passengers: []
  Entity's Vehicle: null
Stacktrace:
  at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
  at knot//net.minecraft.class_3218.method_31420(class_3218.java:408)
  at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
  at knot//net.minecraft.class_3218.method_18765(class_3218.java:372)
  at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
  at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
  at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
  at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
  at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
  at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
  All players: 1 total; [class_3222['Raphcio'/3980, l='ServerLevel[Pigger]', x=-141.76, y=72.00, z=-61.86]]
  Chunk stats: 3025
  Level dimension: minecraft:overworld
  Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
  Level time: 2861 game time, 2861 day time
  Level name: Pigger
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: true
  Level weather: Rain time: 56661 (now: false), thunder time: 84430 (now: false)
  Known server brands: fabric
  Removed feature flags: 
  Level was modded: true
  Level storage version: 0x04ABD - Anvil
  Loaded entity count: 341
Stacktrace:
  at knot//net.minecraft.class_3218.method_8538(class_3218.java:1693)
  at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
  at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
  at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
  at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
  at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
  at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
  Minecraft Version: 1.21
  Minecraft Version ID: 1.21
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 21.0.2, Microsoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
  Memory: 2663256768 bytes (2539 MiB) / 5502926848 bytes (5248 MiB) up to 9663676416 bytes (9216 MiB)
  CPUs: 12
  Processor Vendor: GenuineIntel
  Processor Name: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
  Identifier: Intel64 Family 6 Model 167 Stepping 1
  Microarchitecture: Rocket Lake
  Frequency (GHz): 2.59
  Number of physical packages: 1
  Number of physical CPUs: 6
  Number of logical CPUs: 12
  Graphics card #0 name: NVIDIA GeForce RTX 3060
  Graphics card #0 vendor: NVIDIA
  Graphics card #0 VRAM (MiB): 12288.00
  Graphics card #0 deviceId: VideoController1
  Graphics card #0 versionInfo: 32.0.15.6614
  Memory slot #0 capacity (MiB): 8192.00
  Memory slot #0 clockSpeed (GHz): 3.20
  Memory slot #0 type: DDR4
  Memory slot #1 capacity (MiB): 8192.00
  Memory slot #1 clockSpeed (GHz): 3.20
  Memory slot #1 type: DDR4
  Virtual memory max (MiB): 31069.48
  Virtual memory used (MiB): 22923.38
  Swap memory total (MiB): 14848.00
  Swap memory used (MiB): 1220.08
  Space in storage for jna.tmpdir (MiB): <path not set>
  Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
  Space in storage for io.netty.native.workdir (MiB): <path not set>
  Space in storage for java.io.tmpdir (MiB): available: 52829.22, total: 487498.06
  Space in storage for workdir (MiB): available: 52829.22, total: 487498.06
  JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216M -Xms5120M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Fabric Mods: 
    adventurez: AdventureZ 1.4.21
    animal_armor_trims: Animal Armor Trims 2.0.0
    appleskin: AppleSkin 3.0.6+mc1.21
    architectury: Architectury 13.0.8
    armorful: Armorful 3.1.3+1.21
    artifacts: Artifacts 12.0.6
      cardinal-components-base: Cardinal Components API (base) 6.1.0
      cardinal-components-entity: Cardinal Components API (entities) 6.1.0
      com_electronwill_night-config_core: core 3.8.0
      com_electronwill_night-config_toml: toml 3.8.0
      expandability: ExpandAbility 12.0.0
    balm-fabric: Balm 21.0.20
      kuma_api: KumaAPI 21.0.5-SNAPSHOT
    bclib: BCLib 21.0.13
    beautify: Beautify 1.2.1+1.21
    betterclouds: Better Clouds 1.7.5+1.21-fabric
    betterend: Better End 21.0.11
    biomesoplenty: BiomesOPlenty 21.0.0.18
    carryon: Carry On 2.2.1
    chat_heads: Chat Heads 0.13.7
    chunksfadein: Chunks Fade In 2.0.3-1.21
      com_moandjiezana_toml_toml4j: toml4j 0.7.2
    chunky: Chunky 1.4.16
    cicada: CICADA 0.9.1+1.21-1.21.1
    cloth-config: Cloth Config v15 15.0.140
      cloth-basic-math: cloth-basic-math 0.6.1
    collective: Collective 7.87
    continuity: Continuity 3.0.0+1.21
    coroutil: CoroUtil 1.21.0-1.3.7
    cpm: Customizable Player Models 0.6.19a
    creeperoverhaul: Creeper Overhaul 4.0.5
      com_teamresourceful_resourceful-cosmetics-4j: resourceful-cosmetics-4j 1.0.3
    cristellib: Cristel Lib 1.2.8
      blue_endless_jankson: jankson 1.2.3
    croptopia: Croptopia 3.0.9
    dark-loading-screen: Dark Loading Screen 1.6.14
    deeperdarker: Deeper and Darker 1.3.2.1
      customportalapi: Custom Portal Api 0.0.1-beta66-1.21
    doggytalents: Doggy Talents Next 1.18.35
    doubledoors: Double Doors 5.9
    dragonloot: DragonLoot 1.1.6
    dummmmmmy: MmmMmmMmmMmm 1.21-2.0.6
    durabilitytooltip: Durability Tooltip 1.1.5
    dynamic_fps: Dynamic FPS 3.7.7
      net_lostluma_battery: battery 1.3.0
    eatinganimationid: Eating Animation 1.21+1.9.72
    elementa: Elementa 670
    endrem: End Remastered 6.0.2
    entity_model_features: Entity Model Features 2.2.6
    entity_sound_features: Entity Sound Features 0.4
    entity_texture_features: Entity Texture Features 6.2.9
      org_apache_httpcomponents_httpmime: httpmime 4.5.10
    entityculling: EntityCulling 1.7.2
    epherolib: EpheroLib 1.2.0-1.20.4
    essential: Essential 1.3.5.5
    essential-container: essential-container 1.0.0
      essential-loader: essential-loader 1.2.3
    fabric-api: Fabric API 0.102.0+1.21
      fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
      fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
      fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
      fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
      fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
      fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
      fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
      fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
      fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
      fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
      fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
      fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
      fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
      fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
      fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
      fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
      fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
      fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
      fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
      fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
      fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
      fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
      fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
      fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
      fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
      fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
      fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
      fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
      fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
      fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
      fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
      fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
      fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
      fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
      fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
      fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
      fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
      fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
      fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
      fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
      fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
      fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
      fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
      fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
      fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
      fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
      fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
      fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
    fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0
      org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0
      org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0
      org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0
      org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0
      org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1
      org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
      org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
      org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
      org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0
      org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0
      org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
      org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
      org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
    fabricloader: Fabric Loader 0.16.9
      mixinextras: MixinExtras 0.4.1
    fallingtree: FallingTree 1.21.0.8
    fastpaintings: Fast Paintings 1.21-1.2.15
    ferritecore: FerriteCore 7.0.0
    firstperson: FirstPerson 2.4.6
    forgeconfigapiport: Forge Config API Port 21.0.8
    friendsandfoes: Friends & Foes 3.0.6
    geckolib: GeckoLib 4 4.5.8
    glitchcore: GlitchCore 2.0.0.3
      net_jodah_typetools: typetools 0.6.3
    guardvillagers: GuardVillagers 2.1.2-1.21
      midnightlib: MidnightLib 1.5.7
    horseexpert: Horse Expert 21.0.0
    icarus: Icarus 4.0.0
    immediatelyfast: ImmediatelyFast 1.3.3+1.21.1
      net_lenni0451_reflect: Reflect 1.3.4
    inventoryprofilesnext: Inventory Profiles Next 2.1.0
    iris: Iris 1.8.0+mc1.21.1
      io_github_douira_glsl-transformer: glsl-transformer 2.0.1
      org_anarres_jcpp: jcpp 1.4.14
      org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
    jade: Jade 15.1.5+fabric
    java: OpenJDK 64-Bit Server VM 21
    jewelry: Jewelry (RPG Series) 2.0.2+1.21.1
      com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
    journeymap: Journeymap 1.21-6.0.0-beta.27
      ar_com_hjg_pngj: pngj 2.1.0
      commonnetworking: Common Network 1.0.16-1.21
      journeymap-api-fabric: JourneyMap API 2.0.0-1.21-SNAPSHOT
    justenoughbreeding: Just Enough Breeding 1.4.0
    libipn: libIPN 6.2.0
    lithium: Lithium 0.13.1
    lootr: Lootr 1.21-1.10.34.86
    magistuarmory: Epic Knights: Shields, Armor and Weapons 9.14
    mcwfences: Macaw's Fences and Walls 1.1.2
    mcwfurnitures: Macaw's Furniture 3.3.0
    mcwwindows: Macaw's Windows 2.3.2
    medieval_buildings: Medieval Buildings 1.0.2
    minecraft: Minecraft 1.21
    modernfix: ModernFix 5.19.1+mc1.21
    modmenu: Mod Menu 11.0.3
      placeholder-api: Placeholder API 2.4.0-pre.2+1.21
    monolib: MonoLib 1.4.1
    moonlight: Moonlight Lib 1.21-2.17.11
    mousetweaks: Mouse Tweaks 2.26
    mr_edf_remastered: Ender Dragon Fight Remastered 5.0-beta4
    mr_improved_inchlingorigin: Origins: Improved Inchling 2.4.1
    mr_true_ending: True Ending: Ender Dragon Overhaul 1-v1.1.2d
    mru: Mineblock's Repeated Utilities 1.0.4+1.21+fabric
    nameplate: Nameplate 1.1.4
    org_jetbrains_annotations: annotations 23.0.0
    owo: o?o 0.12.15+1.21
      io_wispforest_endec: endec 0.1.5
      io_wispforest_endec_gson: gson 0.1.3
      io_wispforest_endec_jankson: jankson 0.1.3
      io_wispforest_endec_netty: netty 0.1.2
    perplayerwanderingtraders: PerPlayerWanderingTraders 1.0.2+1.20.6
    polymorph: Polymorph 1.0.6+1.21.1
      cardinal-components-block: Cardinal Components API (blocks) 6.1.0
    puzzleslib: Puzzles Lib 21.0.28
    ranged_weapon_api: RangedWeaponAPI 2.0.4+1.21.1
    reinfbarrel: Reinforced Barrels 2.5.1+1.21
      reinfcore: Reinforced Core 4.0.1+1.21
    reinfchest: Reinforced Chests 3.0.1+1.21
    resourcefulconfig: Resourcefulconfig 3.0.8
    resourcefullib: Resourceful Lib 3.0.12
      com_teamresourceful_bytecodecs: bytecodecs 1.1.2
      com_teamresourceful_yabn: yabn 1.0.3
    roughlyenoughitems: Roughly Enough Items 16.0.788
      error_notifier: Error Notifier 1.0.11
    roughlyenoughprofessions: Roughly Enough Professions 4.0.1
    sereneseasons: SereneSeasons 10.0.0.6
    showmeyourskin: Show Me Your Skin! 1.11.3+1.21
    sit: Sit 1.21-28
    skinlayers3d: 3d-Skin-Layers 1.7.4
    smallships: Small Ships 2.0.0-b1.5
    sodium: Sodium 0.6.0+mc1.21.1
    sodium-extra: Sodium Extra 0.6.0-beta.3+mc1.21.1
    sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.7
    spell_power: Spell Power Attribute 1.0.5+1.21.1
    stackrefill: Stack Refill 4.5
    structure_pool_api: Structure Pool API 1.1.3+1.21.1
    styled-nicknames: Styled Nicknames 1.6.0+1.21
    styledchat: Styled Chat 2.6.0+1.21
      fabric-permissions-api-v0: fabric-permissions-api 0.3.1
      player-data-api: Player Data API 0.6.0+1.21
      predicate-api: Predicate API 0.5.1+1.21
    supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
    supplementaries: Supplementaries 1.21-3.0.26-beta
      mixinsquared: MixinSquared 0.1.1
    swingthrough: SwingThrough 1.0.5+1.21
    t_and_t: Towns and Towers 1.13.2
    tabtps-fabric: TabTPS 1.3.24
      adventure-platform-fabric: adventure-platform-fabric 5.14.0
        net_kyori_adventure-api: adventure-api 4.17.0
        net_kyori_adventure-key: adventure-key 4.17.0
        net_kyori_adventure-platform-api: adventure-platform-api 4.3.3
        net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.17.0
        net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.17.0
        net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.17.0
        net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.17.0
        net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.17.0
        net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.17.0
        net_kyori_ansi: ansi 1.0.3
        net_kyori_examination-api: examination-api 1.3.0
        net_kyori_examination-string: examination-string 1.3.0
        net_kyori_option: option 1.0.0
      cloud: Cloud 2.0.0-beta.7
        io_leangen_geantyref_geantyref: geantyref 1.3.15
        org_incendo_cloud-brigadier: cloud-brigadier 2.0.0-beta.8
        org_incendo_cloud-core: cloud-core 2.0.0-rc.2
        org_incendo_cloud-minecraft-modded-common-fabric-repack_: cloud-minecraft-modded-common-fabric-repack 2.0.0-beta.7
        org_incendo_cloud-services: cloud-services 2.0.0-rc.2
      com_typesafe_config: config 1.4.3
      net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.17.0
      net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
      net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.17.0
      org_incendo_cloud-minecraft-extras: cloud-minecraft-extras 2.0.0-SNAPSHOT
      org_spongepowered_configurate-core: configurate-core 4.1.2
      org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
    terrablender: TerraBlender 4.0.0.2
    threadtweak: ThreadTweak 0.1.4+mc1.21
    toms_storage: Tom's Simple Storage Mod 2.0.11
    tool_trims: Tool Trims 2.2.2
    travelersbackpack: Traveler's Backpack 10.1.3
    travelerstitles: Traveler's Titles 1.21.1-Fabric-5.1.1
      org_reflections_reflections: reflections 0.10.2
    trinkets: Trinkets 3.10.0
    universalcraft: UniversalCraft 365
    valhelsia_core: Valhelsia Core 1.1.2
    valhelsia_furniture: Valhelsia Furniture 1.1.0
    vigilance: Vigilance 306
    villagernames: Villager Names 8.1
    wakes: Wakes 0.3.0+1.21.1
      com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
      satin: Satin 2.0.0
    watut: What Are They Up To 1.21.0-1.1.3
    waystones: Waystones 21.1.5
    wildfire_gender: Wildfire's Female Gender Mod 3.2.1+1.21
    wover: WorldWeaver 21.0.13
      wover-biome: WorldWeaver - Biome API 21.0.13
      wover-block: WorldWeaver - Block and Item API 21.0.13
      wover-common: WorldWeaver - Common API 21.0.13
      wover-core: WorldWeaver - Core API 21.0.13
      wover-datagen: WorldWeaver - Datagen API 21.0.13
      wover-events: WorldWeaver - Events API 21.0.13
      wover-feature: WorldWeaver - Feature API 21.0.13
      wover-generator: WorldWeaver - World Generator API 21.0.13
      wover-item: WorldWeaver - Item API 21.0.13
      wover-math: WorldWeaver - Math API 21.0.13
      wover-preset: WorldWeaver - World Preset API 21.0.13
      wover-recipe: WorldWeaver - Recipe API 21.0.13
      wover-structure: WorldWeaver - Structure API 21.0.13
      wover-surface: WorldWeaver - Surface API 21.0.13
      wover-tag: WorldWeaver - Tag API 21.0.13
      wover-ui: WorldWeaver - UI API 21.0.13
    wunderlib: WunderLib 21.0.8
    xp_storage: XP Storage 1.6+1.21
      cardinal-components-item: Cardinal Components API (items) 6.1.0
    yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.21-fabric
      com_twelvemonkeys_common_common-image: common-image 3.12.0
      com_twelvemonkeys_common_common-io: common-io 3.12.0
      com_twelvemonkeys_common_common-lang: common-lang 3.12.0
      com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
      com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
      com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
      org_quiltmc_parsers_gson: gson 0.2.1
      org_quiltmc_parsers_json: json 0.2.1
    yigd: You're in Grave Danger 2.4.11
      libgui: LibGui 11.0.0+1.21
        jankson: Jankson 8.0.0+j1.2.3
        libninepatch: LibNinePatch 1.2.0
    yungsapi: YUNG's API 1.21.1-Fabric-5.1.3
      org_javassist_javassist: javassist 3.29.2-GA
  Loaded Shaderpack: Insanity-Shader-Universal-v1.650.zip
    Profile: MEDIUM (+0 options changed by user)
  Server Running: true
  Player Count: 1 / 8; [class_3222['Raphcio'/3980, l='ServerLevel[Pigger]', x=-141.76, y=72.00, z=-61.86]]
  Active Data Packs: vanilla, fabric, adventurez, animal_armor_trims (incompatible), armorful, artifacts, balm-fabric (incompatible), bclib, beautify, betterend, biomesoplenty (incompatible), carryon (incompatible), collective, creeperoverhaul, croptopia, deeperdarker (incompatible), doggytalents (incompatible), dragonloot, dummmmmmy, endrem (incompatible), fabric-convention-tags-v2, fastpaintings, friendsandfoes, guardvillagers, horseexpert (incompatible), icarus, jewelry, lootr, magistuarmory, mcwfences (incompatible), mcwfurnitures (incompatible), mcwwindows (incompatible), medieval_buildings (incompatible), moonlight, mr_edf_remastered, mr_improved_inchlingorigin, mr_true_ending, reinfbarrel, reinfchest, sereneseasons (incompatible), smallships, spell_power, supplementaries, t_and_t, terrablender (incompatible), toms_storage, tool_trims, travelersbackpack, travelerstitles (incompatible), trinkets, valhelsia_furniture, waystones (incompatible), wover-generator, wover-preset, wover-surface, wover-tag, xp_storage, yigd, yungsapi (incompatible), towns_and_towers:resources/t_and_t_waystones_patch, moonlight:mods_dynamic_assets, supplementaries:generated_pack
  Available Data Packs: adventurez, animal_armor_trims (incompatible), armorful, artifacts, balm-fabric (incompatible), bclib, beautify, betterend, betterend:nourish_extensions, betterend:patchouli_extensions, biomesoplenty (incompatible), bundle, carryon (incompatible), collective, creeperoverhaul, croptopia, deeperdarker (incompatible), doggytalents (incompatible), dragonloot, dummmmmmy, endrem (incompatible), fabric, fabric-convention-tags-v2, fastpaintings, friendsandfoes, guardvillagers, horseexpert (incompatible), icarus, jewelry, lootr, magistuarmory, mcwfences (incompatible), mcwfurnitures (incompatible), mcwwindows (incompatible), medieval_buildings (incompatible), moonlight, moonlight:mods_dynamic_assets, mr_edf_remastered, mr_improved_inchlingorigin, mr_true_ending, reinfbarrel, reinfchest, sereneseasons (incompatible), smallships, spell_power, supplementaries, supplementaries:generated_pack, t_and_t, terrablender (incompatible), toms_storage, tool_trims, towns_and_towers:resources/t_and_t_waystones_patch, trade_rebalance, travelersbackpack, travelerstitles (incompatible), trinkets, valhelsia_furniture, vanilla, waystones (incompatible), wover-generator, wover-preset, wover-surface, wover-tag, xp_storage, yigd, yungsapi (incompatible)
  Enabled Feature Flags: minecraft:vanilla
  World Generation: Stable
  World Seed: 2543643937889163762
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
  Launched Version: fabric-loader-0.16.9-1.21
[08:50:23] [Server thread/INFO]: Raphcio lost connection: Server closed
[08:50:23] [Netty Local Client IO #1/INFO]: Disconnected from server, resetting proxy config values
[08:50:23] [Server thread/INFO]: Raphcio left the game
[08:50:23] [Server thread/INFO]: Stopping singleplayer server as player logged out
[08:50:23] [Server thread/INFO]: Saving worlds
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Rafonix\AppData\Roaming\Crystal-Launcher\instances\u.Piga\.minecraft\crash-reports\crash-2024-12-13_08.50.23-server.txt

**Comment by Globox1997** [comment]
Update to 1.1.7
